name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"

jobs:
  release:
    env:
      BUILD_CONFIG: "Release"
      LEAGUE_TOOLKIT_PROJECT: "actions-playground"
      TARGET_FRAMEWORK: "netstandard2.1"

    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x

      - name: Install dependencies
        run: dotnet restore

      - id: get_version
        uses: battila7/get-version-action@v2.2.1

      - name: Build
        run: dotnet build $LEAGUE_TOOLKIT_PROJECT --configuration $BUILD_CONFIG --no-restore /p:TargetFramework=${{ env.TARGET_FRAMEWORK }}
        
      - name: Pack
        run: dotnet pack $LEAGUE_TOOLKIT_PROJECT -c $BUILD_CONFIG /p:Version=${{ steps.get_version.outputs.version-without-v }} /p:TargetFramework=${{ env.TARGET_FRAMEWORK }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET_FRAMEWORK }}
          path: "src/${{ env.LEAGUE_TOOLKIT_PROJECT }}/bin/${{ env.BUILD_CONFIG }}/${{ env.TARGET_FRAMEWORK }}/"
      
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: "src/${{ env.LEAGUE_TOOLKIT_PROJECT }}/bin/${{ env.BUILD_CONFIG }}/${{ env.TARGET_FRAMEWORK }}/"
          filename: "${{ env.TARGET_FRAMEWORK }}.zip"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create-tag.outputs.tag }}
          prerelease: ${{ steps.get_version.outputs.prerelease != '' }}
          append_body: true
          files: "${{ env.TARGET_FRAMEWORK }}.zip"
